### ISSUE TITLE
day system

### ISSUE THREAD

**Issue by neutronflare1** [Jpierrot/Shunger-Game#2]
날씨와는 다르다 날씨와는 ㅇㅇㅇㅇㅇㅇ
아침 점심 저녁은 clear, rainy, night가 아니란 말이다

**Comment by Jpierrot** [comment]
음 뭐 하라는지는 알겠는데
내용 좀 성의있게 써보자

**Comment by Jpierrot** [comment]
지금 일자 변경이랑, 시간대별로 이미지 변경 정도로 구현 해놨는데
날짜에서 더 구현되야할 내용 있나

**Comment by Jpierrot** [comment]
더 없으면 여기서 이슈 닫는다?
