### ISSUE TITLE
지지율 시스템 구현

### ISSUE THREAD

**Issue by Jpierrot** [Jpierrot/Shunger-Game#5]
View : 각 지역별로 캐릭터의 지지율을 나타내는 그래프 구현하기.

model : 6개의 각각의 지역 당 랜덤으로 선호하는 캐릭터를 지정.
각 지역별로 있는 요소는 '호감도'와 '지지율'이 있음.(최저 지지율의 개념도 존재)

(전체 지지율 - 최저 지지율)의 값은 호감도에 따라서 증가.
호감도가 0이 되지 않는 한, 최저 지지율은 그대로 유지됨.

**Comment by neutronflare1** [comment]
호감도는 뭔가요??

**Comment by Jpierrot** [comment]
각 지역은 후보 별로 서로 다른 호감도를 지니고 있으며,
호감도에 따라서 후보의 지지율이 증감됨.
각 지역의 지지율은 (최저 지지율 + (후보 호감도/모든 호감도 * 나머지 지지율))로 결정.

**Comment by Jpierrot** [comment]
model 구현 완료

**Comment by Jpierrot** [comment]
막대 그래프까지 완성

**Comment by Jpierrot** [comment]
사실상 라인만 그리면 기능 완성이라 이슈는 마감해도 될듯
